# iNeuron Python Assignment - 3

## Task 1:

### Problem -1 : Write a function to compute 5/0 and use try/except to catch the exceptions.

In [12]:
def divide():
    return 5/0
try:
    divide()
except ZeroDivisionError as ze:
    print("Division by ZERO is always an ERROR")
except :
    print("Any other exception")

Division by ZERO is always an ERROR


### Problem - 2 : Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

### Hint: Subject,Verb and Object should be declared in the program as shown below.
### subjects=["Americans ","Indians"]
### verbs=["play","watch"]
### objects=["Baseball","Cricket"]

In [13]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [14]:
All_sentences = [(sub+" "+verb+" "+obj) for sub in subjects for verb in verbs for obj in objects]
for sentence in All_sentences:
    print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

### Problem - 1 : Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [16]:
# creating a matrix with output coloumn based on input vector(N)

import numpy as np
x = np.array([1,2,3,4,5])
N = 5
matrix = np.column_stack(x**(N-i-1) for i in range(N))
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


C:\Users\DBSOM-L490-10\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  


In [17]:
# Similar matrix is created using np.vander function in numpy

import numpy as np
x = np.array([1,2,3,4,5])
N = 5
matrix1 = np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [18]:
# The determitant for both the matrixs is the same
np.linalg.det(matrix)

287.9999999999977

In [19]:
np.linalg.det(matrix1)

287.9999999999977